name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:     # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Toshaksha
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit and push to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "ğŸ Generate contribution graph snake"
          add: "output/*"
